pipelines:
  api-eventos:
    group: EjercicioTDD
    materials:
      repo:
        git: https://github.com/rdparedes/ejercicio-tdd-python
        branch: master
    stages:
      - pruebas:
          jobs:
            pruebas_unitarias:
              resources:
                - rpibase
            tasks:
                - exec:
                    command: echo
                    arguments:
                      - holi
