pipelines:
  EjercicioTDD:
    group: Ejercicios
    materials:
      repo:
        git: https://github.com/rdparedes/ejercicio-tdd-python
        branch: master
    stages:
      - pruebas:
          jobs:
            pruebas_unitarias:
              tasks:
                  - exec:
                      command: echo
                      arguments:
                        - holi
